### ISSUE TITLE
The protocol of this plugin (protocol version 4 and lower) was deprecated

### ISSUE THREAD

**Issue by semtyre** [martezr/packer-provisioner-puppet-bolt#17]
Hi @martezr,

I would like to use this plugin with some newer plugins.
Sadly `packer >= 1.7` refuses to load it.
```
Error: failed loading puppet-bolt

  on demo2.json.pkr.hcl line 15:
  (source code not available)

The protocol of this plugin (protocol version 4 and lower) was deprecated,
please use a newer version of this plugin. Or use an older version of Packer (pre
1.7) with this plugin.

Error: failed loading puppet-bolt

  on demo2.json.pkr.hcl line 20:
  (source code not available)

The protocol of this plugin (protocol version 4 and lower) was deprecated,
please use a newer version of this plugin. Or use an older version of Packer (pre
1.7) with this plugin.

==> Wait completed after 4 microseconds

==> Builds finished but no artifacts were created.
``` 

Do you plan to upgrade the plugin to work with newer `packer` releases?
I would really like to see `puppet bolt` with `packer` in action 😁

Best regards,

Semtyre

**Comment by martezr** [comment]
@semtyre There is a new version of the plugin that aligns with the changes HashiCorp made to the Packer plugin architecture. The plugin is in a different repository to align with the naming standards for the new plugin - https://github.com/martezr/packer-plugin-bolt
