### ISSUE TITLE
Add Windows support via WinRM (SSL)

### ISSUE THREAD

**Issue by martezr** [martezr/packer-provisioner-puppet-bolt#2]
Add support for provisioning Windows workloads using WinRM configured with SSL

**Comment by bishopbm1** [comment]
@martezr this was resolved in PR https://github.com/martezr/packer-provisioner-puppet-bolt/pull/10

Can a new release be added? I am willing to help out if needed.

**Comment by martezr** [comment]
@bishopbm1 A new release has been created - https://github.com/martezr/packer-provisioner-puppet-bolt/releases/tag/v0.2.0

**Comment by bishopbm1** [comment]
Thank you!
