### ISSUE TITLE
Update to latest bolt API

### ISSUE THREAD

**Issue by dontlaugh** [martezr/packer-provisioner-puppet-bolt#9]
I didn't include this in my PR, but I think to use the latest bolt, there will be some changes required. Hopefully not too many:

https://puppetlabs.github.io/bolt/2020-01-09-new-year-new-bolt

**Comment by martezr** [comment]
@dontlaugh At a quick glance the reference to --nodes needs to be changed to --targets. I think that's probably the only change that needs to take place.

**Comment by bishopbm1** [comment]
This is solved in PR https://github.com/martezr/packer-provisioner-puppet-bolt/pull/10

**Comment by dontlaugh** [comment]
:+1:
